services:
  bienestar-app:
    build: .
    container_name: bienestar-app
    restart: always
    ports:
      - "3014:3000"
    environment:
      - NODE_ENV=production
    networks:
      - tea-network

networks:
  tea-network:
    external: true
